version: '3'
services:

  mysql-container:
    container_name: mysql-container
    image: mysql
    ports:
      - 8081:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musicstreaming
    networks: 
      - springboot-mysql

  springboot-container:
    container_name: springboot-container
    image: springboot
    ports:
      - 8080:8080
    depends_on:
      - mysql-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/musicstreaming
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - springboot-mysql


networks:
  springboot-mysql:
    driver: bridge
