apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: webapp
spec:
  type: LoadBalancer
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
